const SliderData = [
    {
      id: "1",
      icon: "./assets/dotdash.webp",
      company: "Dotdash",
      title: "Frontend Developer",
      date: "May 2021 - August 2022",
      desc1: "Implement features for web applications using Vue, SASS, JavaScript with a responsive web design releasing the first digital issue that increased mobile traffic by 11%",
      desc2: "Created and maintained functionality to a custom server-side component framework. Most recent work includes successfully launching a mulch calculator for usability; Improved customer engagement by 4%",
      desc3: "Worked in an agile environment with a daily stand-up, kept track of user stories/bugs in the Jira board, and conducted 1 hour of sprint planning and sprint retrospective each sprint.",
      desc4: "Participated in each step of the product development process from plannings to deployment used in media websites that reach 150M+ people each month.",
      img: "https://99designs-blog.imgix.net/blog/wp-content/uploads/2018/10/attachment_100040756-e1538485934255.jpeg?auto=format&q=60&fit=max&w=930",
    },
    {
      id: "2",
      icon: "./assets/thales.png",
      company: "Thales",
      title: "Software Engineer Intern",
      date: "Jan - August 2020",
      desc1: "Experience building a Client-Server Architecture using Python/Django.",
      desc2: "Implement features to a custom website framework used for all the branches in the engineering teams. Featured resulted in an estimated 63% reduction in user workload. ",
      desc3: "Worked with internal and external stakeholders to transform product requirements into detailed design.",
      desc4: "Improved performance of data manipulation and analysis. Improvements reduced total time consumption and improved runtime performance by approximately 40%. Used a Python library like Pandas to provide improvements in Python application.",
      img: "https://i.pinimg.com/originals/e9/c9/2f/e9c92f7869d682a6fa5a97fb8a298f30.jpg",
    },
    {
      id: "3",
      icon: "./assets/AI4Youth.webp",
      company: "Ai4YouthCanada",
      title: "Software Engineer Intern",
      date: "May - August 2019",
      desc1: "Delivered a high-quality VR simulation program in a fast-paced environment engaging up to 3 projects.",
      desc2: "Implement features requested by shareholders to multiplatform Python application",
      desc3: "Analyzed and evaluated real-time programs based on defined criteria including utility, relevance, and practicality.",
      desc4: "Developed test application with Unity to verify real-time behavior of the program on a target platform, successfully catching numerous minor bugs, and code violations.",
      img: "https://i.pinimg.com/originals/a9/f6/94/a9f69465d972a004ad581f245d6ad581.jpg",
    },
    {
        id: "4",
        icon: "./assets/uofc.jpeg",
        company: "University of Calgary",
        title: "Research Assistant",
        date: "May - August 2018",
        desc1: "Initiated and coordinated a Text and Data Mining of large dataset extracted from mobile App Development Teams using the program languages Java, Python, R-Language.",
        desc2: "Planned and coordinated NLP Topic Modeling using Python and R-language.",
        desc3: "Improved methods by proposing LDA algorithms and Gibbs Sampling Option that ended up on the final research paper.",
        desc4: "The paper got accepted and published in the IEEE digital library.",
        img: "https://i.pinimg.com/originals/a9/f6/94/a9f69465d972a004ad581f245d6ad581.jpg",
      },
  ];

export default SliderData;